export const iterationStrings = {
 snapshotTooLarge:['This window exceeds the automatic snapshot storage limit. Save it manually or split it into smaller windows.','这个窗口超过自动快照容量，请手动保存或分成较小窗口。'],
  aiConfig:['Choose your AI','选择你的 AI'],aiProvider:['AI service','AI 服务'],aiCustom:['Custom service','自定义服务'],aiProtocol:['API format','接口协议'],aiBaseUrl:['Service address','服务地址'],aiKey:['AI API Key','AI API Key'],aiTest:['Test connection','测试连接'],aiTesting:['Testing connection…','正在测试连接…'],aiConnected:['Connected. This service can respond with the selected model.','连接成功，所选服务和模型可以正常响应。'],
  aiSetupDesc:['Connect OpenAI, Anthropic or a compatible service. Customize the address and model. You can test the connection before upgrading.','连接 OpenAI、Anthropic 或兼容接口的服务，可自定义地址和模型。升级前即可测试连接。'],
  aiKeyNote:['Your API key stays on this device, is excluded from backups, and goes only to your selected service. AI calls are billed by that service. Local models can use an empty key.','API Key 保存在本机，不进入备份，仅发送至你选择的服务。调用费用由该服务商收取，本地模型可不填 Key。'],
  aiDisclosure:['Your instruction and task titles, dates and tags go directly to your selected AI service. Review every change before applying.','你的指令和任务标题、日期、标签会发送至所选 AI 服务，应用前请核对每个修改。'],
  aiNoKey:['Configure your AI service and API key in Settings first.','请先在设置中配置 AI 服务和 API Key。'],aiPermission:['Network permission was not granted for this service.','未授予这个服务的联网权限。'],aiInvalidConfig:['Check the API format and key.','请检查接口协议和 API Key。'],aiInvalidUrl:['Enter an HTTPS service address, or a local HTTP address.','请输入 HTTPS 服务地址，或本机 HTTP 地址。'],aiInvalidModel:['Enter a model name.','请输入模型名称。'],aiInvalidKey:['The service rejected the key or access. Check the key and permissions.','服务拒绝了密钥或访问权限，请检查 API Key 和权限。'],aiModelUnavailable:['The model or endpoint was not found. Check the model and service address.','找不到模型或接口，请检查模型名称和服务地址。'],aiRateLimit:['The service reached its usage or rate limit. Check your balance and retry later.','服务额度或请求频率已达上限，请检查余额并稍后重试。'],aiServiceError:['The AI service could not complete the request. Please retry.','AI 服务暂时无法完成请求，请重试。'],aiNetwork:['Could not reach the service. Check the address and network.','无法连接服务，请检查地址和网络。'],
  taskDataNote:['Tasks stay on this browser. Optional AI sends only the instruction and task snapshot to the service you select. Your API key is excluded from backups.','任务保存在本浏览器。可选 AI 仅将指令与任务快照发送至所选服务，API Key 不进入备份。'],
  proTaskFeatures:['Unlimited active tasks and lists|Task tags and page excerpts|Backup import and export|Connect your preferred AI to create and organize tasks','无限活动任务和列表|任务标签与网页摘要|备份导入和导出|连接你常用的 AI，生成和整理任务'],
  proVaultFeatures:['Unlimited sessions, organized by project|Automatic local snapshots: up to 30 days|Restore windows and browser tab groups|Notes, tags and batch organization','无限保存会话，按项目整理资料|自动本地快照，回看最长 30 天|恢复窗口与浏览器标签分组|备注、标签与批量整理'],
  proVaultHeadline:['Keep each project ready to continue.','把每个项目，留在随时能继续的地方。'],proVaultLead:['Save by project. Revisit past tabs. Find your materials faster.','按项目保存，找回过去的标签，更快找到需要的资料。'],proTaskHeadline:['Make room for your next step.','给下一步，留出更多空间。'],proTaskLead:['More tasks, better organization and your choice of AI.','更多任务、更好整理，AI 由你选择。'],proActiveNote:['All Pro features are available on this browser.','本浏览器已解锁全部 Pro 功能。'],explorePro:['Explore Pro','了解 Pro'],managePurchase:['Manage purchase','管理购买'],upgradeTitle:['A little more with Pro.','用 Pro，继续你的节奏。'],upgradeDesc:['One-time purchase. Automatic activation.','一次性买断，付款后自动激活。'],noSubscription:['No subscription','无订阅'],
  buy:['Upgrade Pro · $6','升级 Pro · $6'],buyNote:['Purchases started here activate automatically after payment. No license code to copy. The checkout page shows any applicable tax.','从这里发起购买，付款后自动激活，无需复制授权码。适用税费以结账页为准。'],aiBillingNote:['The Pro purchase does not include AI usage. Connect your own API key; your provider bills AI calls separately.','Pro 买断不包含 AI 调用费用。请连接自己的 API Key，调用费用由服务商另行收取。'],
  license:['Pro license code','Pro 授权码'],licensePlaceholder:['Paste your existing license code','粘贴已有的 Pro 授权码'],haveLicense:['Have a license code?','已有授权码？'],restorePurchase:['Restore purchase','恢复购买'],purchaseEmail:['Purchase email','购买邮箱'],sendRecoveryCode:['Send verification code','发送验证码'],recoveryCode:['Verification code','验证码'],recoveryDesc:['Enter the email used at checkout. If it has an eligible purchase, a code will arrive. Existing license codes also work below.','输入结账时使用的邮箱。如果存在可恢复的购买，将收到验证码。也可在下方使用已有授权码。'],recoverySent:['If this email has an eligible purchase, a code has been sent. It is valid for 10 minutes.','如果这个邮箱有可恢复的购买，验证码已发送，10 分钟内有效。'],recoveryInvalid:['The code is incorrect, expired or already used. Request a new code.','验证码不正确、已过期或已使用，请重新获取。'],recoveryRateLimit:['Too many requests. Please wait before trying again.','请求过于频繁，请稍后再试。'],recoveryUnavailable:['Email recovery is not available yet. Use your saved license or contact support.','邮件恢复暂未配置，可使用已保存的授权码或联系支持。'],
  billingOpening:['Opening checkout…','正在打开结账页…'],billingWaiting:['Waiting for payment confirmation…','正在等待付款确认…'],billingCheck:['Check payment status','检查付款状态'],billingWaitNote:['If you have paid, check here. You can close the payment page; your pending purchase stays on this browser.','如果已经付款，可在这里检查。关闭付款页面后，本浏览器仍保留待确认的购买。'],billingUnavailable:['Could not check the payment service. Retry without paying again.','暂时无法核对付款服务，请重试，无需重复付款。'],billingInvalidLicense:['The returned license could not be verified. Contact support; do not pay again.','返回的授权无法验证，请联系支持，无需重复付款。'],billingInvalidClaim:['This purchase notification does not match this browser.','购买通知与本浏览器不匹配。'],billingRefunded:['This order has a refund. Contact support about your license.','该订单存在退款，请联系支持处理授权。'],billingExpired:['This checkout has expired. Start a new purchase.','这次结账已过期，请重新发起购买。'],billingRestart:['Start a new checkout','重新发起购买'],confirmDeactivate:['Remove Pro from this browser? Your saved data stays here.','解除本浏览器的 Pro 授权？已保存的数据会保留。'],
  vaultFreeSummary:['10 manual sessions · title/URL search · JSON backup · 3 recent snapshots','10 个手动会话 · 标题/网址搜索 · JSON 备份 · 最近 3 份快照'],vaultProSummary:['Unlimited sessions · project spaces · history filters · advanced organization','无限会话 · 项目空间 · 历史筛选 · 高级整理'],
  projects:['Projects','项目空间'],allProjects:['All projects','全部项目'],ungrouped:['Unassigned','未分配项目'],newProject:['New project','新建项目'],projectName:['Project name','项目名称'],projectNote:['Project notes','项目备注'],projectColor:['Project color','项目颜色'],projectCreated:['Project created.','项目已创建。'],projectUpdated:['Project updated.','项目已更新。'],projectDeleted:['Project removed. Its sessions are kept.','项目已删除，会话已保留。'],projectEmpty:['Save a session to this project first.','先为这个项目保存一个会话。'],missingProject:['This project no longer exists.','这个项目已不存在。'],projectPro:['Create project spaces with Pro and return to each project in one click.','升级 Pro，创建项目空间，一键继续每个项目。'],organizePro:['Organize sessions with notes, tags and batch tools in Pro.','升级 Pro，使用备注、标签与批量整理。'],restorePro:['Restore browser groups and skip open duplicates with Pro.','升级 Pro，恢复浏览器分组并跳过已打开的重复页面。'],confirmDeleteProject:['Remove this project? Its saved sessions will remain unassigned.','删除这个项目？已保存会话会保留，并移出项目。'],openProject:['Open project windows','打开项目窗口'],projectWindowsOpened:['Opened {n} tabs across {windows} project windows.','已在 {windows} 个项目窗口打开 {n} 个标签。'],
  timeline:['History','恢复时间线'],advancedFilters:['Filter by date and tag','按日期与标签筛选'],fromDate:['From date','开始日期'],toDate:['Through date','结束日期'],filterTag:['Tag contains','标签包含'],historyPro:['Use Pro to browse longer history and filter by date, project and tags.','升级 Pro，回看更长历史，并按日期、项目和标签筛选。'],historyRetention:['Up to 30 days, 500 snapshots and 4 MB of local snapshot storage. Older snapshots roll off when limits are reached.','最长 30 天，最多 500 份快照、本地快照容量 4 MB。达到上限时滚动清理较早快照。'],freeRetention:['Free keeps the 3 most recent snapshots. Manual sessions are never removed by snapshot cleanup.','免费版保留最近 3 份快照，快照清理不会删除手动会话。'],backupPro:['Pro adds longer history, date filters and project organization.','Pro 提供更长历史、日期筛选与项目整理。'],backupOffDesc:['Optional local snapshots for normal browser windows.','可为普通浏览器窗口开启本地快照。'],
  batchOrganize:['Batch organize','批量整理'],selectedSessions:['{n} selected','已选择 {n} 个会话'],selectSession:['Select {name}','选择 {name}'],moveToProject:['Move to project','移至项目'],sessionsMoved:['Selected sessions moved.','所选会话已移动。'],mergeSessions:['Merge into a new session','合并为新会话'],confirmMerge:['Create a combined session? The original sessions will be kept.','生成合并会话？原会话会保留。'],merged:['Combined session saved; originals kept.','合并会话已保存，原会话已保留。'],pinSession:['Pin this session','置顶这个会话'],deduplicate:['Remove duplicate URLs','移除重复网址'],confirmDedup:['Remove repeated URLs from this saved session? The first copy is kept.','从这个会话移除重复网址？保留第一次出现的页面。'],duplicatesRemoved:['Removed {n} duplicate URLs.','已移除 {n} 个重复网址。'],selectTabs:['Select tabs to restore','选择要恢复的标签'],selectAllTabs:['Select all tabs','选择全部标签'],preserveGroups:['Restore browser tab groups · Pro','恢复浏览器标签分组 · Pro'],skipDuplicates:['Skip URLs already open · Pro','跳过已打开的网址 · Pro'],restoreScope:['Restores URLs, tab order, pinned tabs and optional groups. Unsaved page inputs are not saved.','恢复网址、标签顺序、固定状态及可选分组，不保存网页内未提交的输入。'],restoredDetailed:['Restored {n} tabs; skipped {skipped} duplicates.','已恢复 {n} 个标签，跳过 {skipped} 个重复页面。'],sessionUpdated:['Session updated.','会话已更新。'],invalidSelection:['Choose valid saved sessions or tabs.','请选择有效的已保存会话或标签。'],invalidWindow:['Select an available browser window.','请选择可用的浏览器窗口。'],'Invalid tab group':['Invalid browser tab group data.','浏览器标签分组数据不正确。']
};
