import React,{useState,useRef,useEffect} from 'react';
import {motion,AnimatePresence} from 'motion/react';
import {Archive,Monitor,ArrowUpRight,RotateCcw,Search,X,Folder,Clock3,ChevronRight,MoreHorizontal,Pin,ShieldCheck,Layers3,Plus,Check,Trash2,Link2} from 'lucide-react';
import {useWorkspace,Button,Switch,Header,Welcome,PanelSheet,Toast,Loading,Segments,Empty,Footer,Preferences,License,DataSettings,SettingsBrand,Shortcuts,SiteMark,SiteStack,ago,http,domain,download} from './shared';

export function parseLinks(text){return text.split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map(line=>{
 if(http(line))return new URL(line).href;
 if(/^[a-z][a-z\d+.-]*:/i.test(line))return null;
 if(/^[\w-]+(\.[\w-]+)+([/?#].*)?$/.test(line)){const url='https://'+line;return http(url)?new URL(url).href:null}
 return 'https://www.google.com/search?q='+encodeURIComponent(line);
}).filter(Boolean)}
export default function VaultApp(){
 const ws=useWorkspace('tabvault'),{t,state,caps,busy,notify}=ws;
 const [filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[expanded,setExpanded]=useState(null),[sheet,setSheet]=useState(null),[selected,setSelected]=useState(null),[recovery,setRecovery]=useState(null),[format,setFormat]=useState('json');
 const panelRef=useRef(null),fileRef=useRef(null),settings=()=>setSheet('settings'),run=(op,payload)=>ws.rpc(op,payload,{upgrade:settings});
 useEffect(()=>{chrome.storage.local.get('tv_export_format').then(data=>{if(['json','md','csv','txt'].includes(data.tv_export_format))setFormat(data.tv_export_format)})},[]);
 useEffect(()=>{
  let alive=true;chrome.storage.local.get(['tv_startup_hint','tv_crash_dismissed']).then(data=>{const hint=data.tv_startup_hint,at=typeof hint==='number'?hint:hint?.at;const target=hint?.target?state.sessions.find(session=>session.id===hint.target):state.sessions.find(session=>session.auto&&session.createdAt<=at);if(alive)setRecovery(target&&data.tv_crash_dismissed!==target.id?target:null)});return()=>{alive=false};
 },[state.sessions]);
 const manualCount=state.sessions.filter(session=>!session.auto).length,visible=state.sessions.filter(session=>(filter==='all'||(filter==='auto'?session.auto:!session.auto))&&[session.name,...session.tabs.map(tab=>tab.title+' '+tab.url)].join(' ').toLowerCase().includes(query.toLowerCase()));
 const saveWindow=async(andClose=false)=>{const result=await run('SAVE_WINDOW',{windowId:ws.windowInfo.id,andClose});if(result){setFilter('all');setQuery('');notify(t(andClose?'savedClosed':'savedWindow',{n:andClose?Math.max(0,result.session.tabs.length-1):result.session.tabs.length}));ws.refreshTabs()}};
 const openRestore=session=>{setSelected(session.id);setSheet('restore')};
 const dismissRecovery=async()=>{try{if(recovery)await chrome.storage.local.set({tv_crash_dismissed:recovery.id});await chrome.storage.local.remove('tv_startup_hint');setRecovery(null)}catch{notify(t('saveFailed'))}};
 const restore=async(here=false)=>{const result=await run('RESTORE',{id:selected,here,windowId:ws.windowInfo.id});if(result){setSheet(null);notify(t('restored',{n:result.restored}));if(selected===recovery?.id)await dismissRecovery();ws.refreshTabs()}};
 const exportBackup=async()=>{
  if(!caps.export)return settings();const date=new Date().toISOString().slice(0,10),sessions=state.sessions;
  if(format==='json')download(JSON.stringify({app:'tabvault',v:1,sessions},null,2),'tabvault-'+date+'.json');
  else if(format==='md'){const esc=x=>String(x).replace(/[\\\[\]]/g,'\\$&');download(sessions.map(session=>'## '+esc(session.name)+'\n\n'+session.tabs.map(tab=>'- ['+esc(tab.title)+']('+tab.url.replaceAll('(','%28').replaceAll(')','%29')+')').join('\n')).join('\n\n'),'tabvault-'+date+'.md','text/markdown')}
  else if(format==='csv'){const cell=value=>{const raw=String(value??'');return '"'+(/^[=+\-@\t\r]/.test(raw)?"'":'')+raw.replaceAll('"','""')+'"'};const rows=[['session','created','tab_title','tab_url'],...sessions.flatMap(session=>session.tabs.map(tab=>[session.name,new Date(session.createdAt).toISOString(),tab.title,tab.url]))];download('\ufeff'+rows.map(row=>row.map(cell).join(',')).join('\r\n'),'tabvault-'+date+'.csv','text/csv')}
  else{try{await navigator.clipboard.writeText(sessions.map(session=>session.name+'\n'+session.tabs.map(tab=>tab.url).join('\n')).join('\n\n'));return notify(t('copied'))}catch{return notify(t('copyFailed'))}}
  notify(t('backupReady'));
 };
 const importBackup=()=>{if(!caps.export)return settings();fileRef.current?.click()};
 const importFile=async file=>{if(!file)return;if(file.size>10*1024*1024)return notify(t('largeFile'));try{const data=JSON.parse(await file.text());if(data.app&&data.app!=='tabvault')throw new Error();const result=await run('IMPORT',{data});if(result)notify(t('importSessions',{n:result.imported}))}catch{notify(t('badFile',{app:'TabVault'}))}finally{fileRef.current.value=''}};
 const sessionsTabs=ws.windowInfo.tabs,hosts=[...new Set(sessionsTabs.map(tab=>domain(tab.url)))],picked=state.sessions.find(session=>session.id===selected);
 if(!ws.ready||ws.error)return <Loading ws={ws}/>;
 return <section className="app-panel" ref={panelRef} aria-label="TabVault"><Header ws={ws} onSettings={settings}/><main className="app-scroll"><Welcome ws={ws}/>{state.recoveryAvailable&&<div className="notice-banner">{t('recoveryData')}</div>}
  <section className="window-card"><div className="window-card-head"><span className="window-card-title"><Monitor size={16}/>{t('currentWindow')}</span><span className="count-pill">{t('tabs',{n:sessionsTabs.length})}</span></div><div className="window-sites"><SiteStack tabs={sessionsTabs}/><div><b>{hosts.slice(0,3).join(' · ')||t('noTabs')}</b><span>{t('morePages',{n:Math.max(0,sessionsTabs.length-3)})} · {t('pinned',{n:sessionsTabs.filter(tab=>tab.pinned).length})}</span></div></div><Button id="btnSave" className="primary-action" disabled={busy||!sessionsTabs.length} onClick={()=>saveWindow()}><Archive/>{t('saveWindow')}<span className="shortcut">Alt ⇧ S</span></Button><Button id="btnSaveClose" variant="ghost" className="save-close" disabled={busy||!sessionsTabs.length} onClick={()=>saveWindow(true)}>{t('saveClose')}<ArrowUpRight size={13}/></Button></section>
  <AnimatePresence>{recovery&&<motion.section key="recovery" className="recovery-card" initial={false} exit={{height:0,opacity:0}} transition={ws.transition}><span className="recovery-symbol"><RotateCcw size={16}/></span><div><b>{t('recoveryTitle')}</b><span>{recovery.name} · {t('tabs',{n:recovery.tabs.length})}</span></div><Button variant="ghost" className="recovery-button" onClick={()=>openRestore(recovery)}>{t('restore')}<ArrowUpRight size={13}/></Button><Button variant="ghost" className="dismiss" size="icon-xs" aria-label={t('dismiss')} onClick={dismissRecovery}><X size={12}/></Button></motion.section>}</AnimatePresence>
  <div className="list-controls"><Segments value={filter} onChange={setFilter} label={t('sessions')} items={[{id:'all',label:t('all'),count:state.sessions.length},{id:'manual',label:t('manual')},{id:'auto',label:t('auto')}]}/></div>
  <div className="input-row"><Search size={16}/><input id="searchBox" aria-label={t('searchVaultLabel')} placeholder={caps.search?t('searchSessions'):t('searchProPlaceholder')} value={query} onChange={e=>{if(!caps.search&&e.target.value){notify(t('proFeature'));settings();return}setQuery(e.target.value)}}/>{query&&<Button variant="ghost" size="icon-xs" aria-label={t('clearSearch')} onClick={()=>setQuery('')}><X size={12}/></Button>}</div>
  <div className="list-heading"><span>{t('recent')}</span><span>{t('sessionCount',{n:visible.length})}</span></div>
  <div className="session-list"><AnimatePresence initial={false} mode="popLayout">{visible.map(session=><motion.article key={session.id} data-id={session.id} className={'session-card '+(expanded===session.id?'expanded':'')} layout initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,height:0}} transition={ws.transition}>
   <div className="session-card-top"><span className={'session-symbol '+(session.auto?'automatic':'')}>{session.auto?<Clock3 size={19}/>:<Folder size={19}/>}</span><button className="session-title" aria-expanded={expanded===session.id} onClick={()=>setExpanded(expanded===session.id?null:session.id)}><b>{session.name}</b><span>{t('tabs',{n:session.tabs.length})}<span className="meta-sep">·</span>{ago(session.createdAt,ws)}</span></button><Button variant="ghost" size="icon-xs" className="session-more" aria-label={t('editSession',{name:session.name})} onClick={()=>{setSelected(session.id);setSheet('session')}}><MoreHorizontal size={15}/></Button><Button variant="ghost" size="icon-sm" className="expand-button" aria-label={t('expand',{name:session.name})} aria-expanded={expanded===session.id} onClick={()=>setExpanded(expanded===session.id?null:session.id)}><motion.span animate={{rotate:expanded===session.id?90:0}}><ChevronRight size={16}/></motion.span></Button></div>
   {expanded!==session.id&&<div className="session-sites-summary"><SiteStack tabs={session.tabs}/><span>{t(session.auto?'autoSnapshot':'manualSaved')}</span><Button variant="ghost" className="mini-restore" onClick={()=>openRestore(session)}>{t('restore')}<ArrowUpRight size={13}/></Button></div>}
   <AnimatePresence initial={false}>{expanded===session.id&&<motion.div className="session-expand" initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} transition={ws.transition}><div className="session-tab-list">{session.tabs.map((tab,index)=><div className="saved-tab" key={index}><SiteMark url={tab.url}/><a href={tab.url} target="_blank" rel="noopener noreferrer" title={tab.url}><b>{tab.title}</b><span>{domain(tab.url)}</span></a>{tab.pinned&&<Pin size={12} aria-label={t('pinned',{n:1})}/>}</div>)}</div><div className="session-action-row"><span><ShieldCheck size={12}/>{t('local')}</span><Button variant="outline" className="restore-action" onClick={()=>openRestore(session)}><RotateCcw size={13}/>{t('restoreSession')}</Button></div></motion.div>}</AnimatePresence>
  </motion.article>)}</AnimatePresence></div>{!visible.length&&<Empty ws={ws} search={!!query}/>}
  <div className="backup-setting"><span className="backup-icon"><ShieldCheck size={17}/></span><div><b>{t(state.settings.autoOn&&ws.isPro?'autoOn':'autoOff')}</b><span>{ws.isPro?t('backupSchedule',{n:state.settings.intervalMin,max:CONFIG.PRO.keepAutoBackups}):t('backupPro')}</span></div><Switch id="chkAuto" aria-label={t('autoBackup')} checked={state.settings.autoOn&&ws.isPro} disabled={busy} onCheckedChange={async enabled=>{if(await run('SETTINGS',{autoOn:enabled}))notify(t(enabled?'autoOn':'autoOff'))}}/></div>
 </main><Footer ws={ws} onExport={exportBackup} onImport={importBackup}><Button variant="ghost" size="icon-xs" id="btnPaste" aria-label={t('paste')} title={t('paste')} onClick={()=>setSheet('paste')}><Link2 size={14}/></Button></Footer><input id="fileImport" type="file" hidden ref={fileRef} accept=".json,application/json" onChange={e=>importFile(e.target.files?.[0])}/>{!sheet&&<Toast ws={ws}/>}
 <PanelSheet ws={ws} panelRef={panelRef} open={!!sheet} onClose={()=>setSheet(null)} title={t(sheet==='settings'?'settingsTitle':sheet==='restore'?'restoreTitle':sheet==='paste'?'pasteTitle':'renameTitle')} description={t(sheet==='settings'?'settingsDesc':sheet==='restore'?'restoreDesc':sheet==='paste'?'pasteDesc':'local')}>
  {sheet==='settings'&&<><SettingsBrand ws={ws}/><Preferences ws={ws}/><VaultSettings ws={ws} run={run}/><DataSettings ws={ws} onExport={exportBackup} onImport={importBackup}/><label className="form-label">{t('exportFormat')}<select value={format} onChange={async e=>{const value=e.target.value;try{await chrome.storage.local.set({tv_export_format:value});setFormat(value)}catch{notify(t('saveFailed'))}}}><option value="json">JSON</option><option value="md">Markdown</option><option value="csv">CSV</option><option value="txt">{t('copy')}</option></select></label><License ws={ws}/><Shortcuts ws={ws}/></>}
  {sheet==='restore'&&(picked?<><div className="restore-summary"><span className="large-folder"><Folder size={28}/></span><h3>{picked.name}</h3><p>{t('tabs',{n:picked.tabs.length})} · {ago(picked.createdAt,ws)}</p><SiteStack tabs={picked.tabs}/></div><Button variant="outline" className="restore-choice" disabled={busy} onClick={()=>restore(false)}><Monitor/><div><b>{t('newWindow')}</b><span>{t('newWindowDesc')}</span></div><ArrowUpRight/></Button><Button variant="outline" className="restore-choice" disabled={busy||ws.windowInfo.id==null} onClick={()=>restore(true)}><Layers3/><div><b>{t('here')}</b><span>{t('hereDesc')}</span></div><Plus/></Button><div className="quiet-info"><ShieldCheck size={15}/><span>{t(state.settings.delAfterRestore&&!picked.auto?'removedSession':'keptSession')}</span></div></>:<Empty ws={ws}/>)}
  {sheet==='session'&&<SessionEditor key={selected} ws={ws} session={picked} run={run} onClose={()=>setSheet(null)}/>}
  {sheet==='paste'&&<PastePanel ws={ws} run={run} onSaved={()=>{setFilter('all');setQuery('');setSheet(null)}}/>}
 </PanelSheet></section>
}
function VaultSettings({ws,run}){const [interval,setInterval]=useState(String(ws.state.settings.intervalMin)),{t,state}=ws;return <div className="settings-section"><h4>{t('backup')}</h4><div className="preference-row"><div><b>{t('autoBackup')}</b><span>{t('backupSchedule',{n:state.settings.intervalMin,max:CONFIG.PRO.keepAutoBackups})}</span></div><Switch aria-label={t('autoBackup')} checked={state.settings.autoOn&&ws.isPro} disabled={ws.busy} onCheckedChange={value=>run('SETTINGS',{autoOn:value})}/></div><p className="settings-note">{t('backupKept')}</p><form style={{marginTop:18}} onSubmit={async e=>{e.preventDefault();if(await run('SETTINGS',{intervalMin:Number(interval)}))ws.notify(t('preferencesSaved'))}}><label className="form-label">{t('interval')}<input type="number" min="1" step="1" value={interval} onChange={e=>setInterval(e.target.value)}/></label><Button variant="outline" type="submit" disabled={ws.busy||!interval||!Number.isFinite(Number(interval))||Number(interval)<1}>{t('save')}</Button></form><div className="preference-row" style={{marginTop:22}}><div><b>{t('deleteAfter')}</b><span>{t('deleteAfterNote')}</span></div><Switch aria-label={t('deleteAfter')} checked={state.settings.delAfterRestore} disabled={ws.busy} onCheckedChange={value=>run('SETTINGS',{delAfterRestore:value})}/></div></div>}
function SessionEditor({ws,session,run,onClose}){const [name,setName]=useState(session?.name||''),{t}=ws;if(!session)return <Empty ws={ws}/>;return <><div className="session-edit-summary"><SiteStack tabs={session.tabs}/><span>{t('tabs',{n:session.tabs.length})} · {ago(session.createdAt,ws)}</span></div><label className="form-label">{t('rename')}<input maxLength={80} disabled={session.auto} value={name} onChange={e=>setName(e.target.value)}/></label>{!session.auto&&<><Button className="primary-action" disabled={ws.busy||!name.trim()} onClick={async()=>{if(await run('RENAME',{id:session.id,name:name.trim()})){onClose();ws.notify(t('renamed'))}}}>{t('save')}<Check size={15}/></Button><Button variant="outline" className="danger-action" disabled={ws.busy} onClick={async()=>{if(confirm(t('confirmDeleteSession'))&&await run('DELETE',{id:session.id})){onClose();ws.notify(t('deleted'))}}}><Trash2 size={14}/>{t('deleteSession')}</Button></>}</>}
function PastePanel({ws,run,onSaved}){
 const [input,setInput]=useState(''),[working,setWorking]=useState(false),{t}=ws;
 const save=async()=>{const urls=parseLinks(input);if(!urls.length)return ws.notify(t('pasteNone'));const tabs=urls.map(url=>({title:domain(url)+new URL(url).pathname,url,fav:'',pinned:false}));if(await run('PASTE',{tabs})){ws.notify(t('savedWindow',{n:tabs.length}));onSaved()}};
 const open=async()=>{const urls=parseLinks(input);if(!urls.length)return ws.notify(t('pasteNone'));setWorking(true);let opened=0;try{for(const url of urls){await chrome.tabs.create({windowId:ws.windowInfo.id,url,active:false});opened++}ws.notify(t('opened',{n:opened}));ws.refreshTabs();onSaved()}catch{ws.notify(t('partialOpen',{n:opened,total:urls.length}))}finally{setWorking(false)}};
 return <><label className="form-label">{t('webLinks')}<textarea id="pasteInput" rows={7} value={input} onChange={e=>setInput(e.target.value)} placeholder={'https://example.com/article\nexample.org\n'+t('search')} disabled={working}/></label><Button id="btnPasteSave" className="primary-action" disabled={ws.busy||working||!input.trim()} onClick={save}><Archive size={16}/>{t('saveAsSession')}</Button><Button id="btnPasteOpen" variant="outline" style={{marginTop:12,width:'100%'}} disabled={working||!input.trim()||ws.windowInfo.id==null} onClick={open}>{t('openLinks')}<ArrowUpRight size={14}/></Button></>
}
