import React,{useState,useRef,useEffect} from 'react';
import {motion,AnimatePresence} from 'motion/react';
import {Archive,Monitor,ArrowUpRight,RotateCcw,Search,X,Folder,Clock3,MoreHorizontal,Pin,ShieldCheck,Layers3,Plus,Check,Trash2,Link2,Filter} from 'lucide-react';
import {useWorkspace,Button,Switch,Header,Welcome,PanelSheet,Toast,Loading,Segments,Empty,Footer,Preferences,License,DataSettings,SettingsBrand,Shortcuts,SiteStack,ago,http,domain,download} from './shared';
import {UpgradePanel} from './billing-panel';

export function parseLinks(text){return text.split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map(line=>{
 if(http(line))return new URL(line).href;if(/^[a-z][a-z\d+.-]*:/i.test(line))return null;
 if(/^[\w-]+(\.[\w-]+)+([/?#].*)?$/.test(line)){const url='https://'+line;return http(url)?new URL(url).href:null}
 return 'https://www.google.com/search?q='+encodeURIComponent(line);
}).filter(Boolean)}
const dayOf=timestamp=>new Date(timestamp).toLocaleDateString('sv-SE');

export default function VaultApp(){
 const ws=useWorkspace('tabvault'),{t,state,caps,busy,notify}=ws;
 const [filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[expanded,setExpanded]=useState(null),[sheet,setSheet]=useState(null),[selected,setSelected]=useState(null),[recovery,setRecovery]=useState(null),[format,setFormat]=useState('json');
 const [project,setProject]=useState('all'),[showFilters,setShowFilters]=useState(false),[from,setFrom]=useState(''),[to,setTo]=useState(''),[tag,setTag]=useState(''),[batch,setBatch]=useState(false),[checked,setChecked]=useState([]),[reason,setReason]=useState('');
 const [indices,setIndices]=useState([]),[preserveGroups,setPreserveGroups]=useState(false),[skipDuplicates,setSkipDuplicates]=useState(false);
 const panelRef=useRef(null),fileRef=useRef(null),settings=()=>setSheet('settings'),upgrade=why=>{setReason(typeof why==='string'?why:'');setSheet('upgrade')},run=(op,payload)=>ws.rpc(op,payload,{upgrade:()=>upgrade(op.startsWith('PROJECT')?'projectPro':op==='RESTORE'?'restorePro':'organizePro')});
 useEffect(()=>{chrome.storage.local.get('tv_export_format').then(data=>{if(['json','md','csv','txt'].includes(data.tv_export_format))chrome.runtime.sendMessage({type:'TV_OP',op:'READ'}).then(result=>{if(result?.state.plan==='pro')setFormat(data.tv_export_format)})})},[]);
 useEffect(()=>{if(!ws.isPro){setFormat('json');setShowFilters(false);setFrom('');setTo('');setTag('');setBatch(false);setChecked([])}},[ws.isPro]);
 useEffect(()=>{setChecked(ids=>ids.filter(id=>state.sessions.some(session=>session.id===id&&!session.auto)));if(project!=='all'&&project!==''&&!state.projects?.some(item=>item.id===project))setProject('all')},[state.sessions,state.projects,project]);
 useEffect(()=>{let alive=true;chrome.storage.local.get(['tv_startup_hint','tv_crash_dismissed']).then(data=>{const hint=data.tv_startup_hint,at=typeof hint==='number'?hint:hint?.at;const target=hint?.target?state.sessions.find(session=>session.id===hint.target):state.sessions.find(session=>session.auto&&session.createdAt<=at);if(alive)setRecovery(target&&data.tv_crash_dismissed!==target.id?target:null)});return()=>{alive=false}},[state.sessions]);
 const manualCount=state.sessions.filter(session=>!session.auto).length,projects=state.projects||[];
 const visible=state.sessions.filter(session=>(filter==='all'||(filter==='auto'?session.auto:!session.auto))&&(project==='all'||session.projectId===project)&&(!from||dayOf(session.createdAt)>=from)&&(!to||dayOf(session.createdAt)<=to)&&(!tag||session.tags.some(value=>value.toLowerCase().includes(tag.toLowerCase())))&&[session.name,...session.tabs.map(tab=>tab.title+' '+tab.url),...(ws.isPro?[session.note,...session.tags]:[])].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.createdAt-a.createdAt);
 const picked=state.sessions.find(session=>session.id===selected),sessionsTabs=ws.windowInfo.tabs,hosts=[...new Set(sessionsTabs.map(tab=>domain(tab.url)))];
 const saveWindow=async(andClose=false)=>{const result=await run('SAVE_WINDOW',{windowId:ws.windowInfo.id,andClose,projectId:project==='all'?'':project});if(result){setFilter('manual');setQuery('');notify(t(andClose?'savedClosed':'savedWindow',{n:andClose?Math.max(0,result.session.tabs.length-1):result.session.tabs.length}));ws.refreshTabs()}};
 const openRestore=session=>{setSelected(session.id);setIndices(session.tabs.map((_,index)=>index));setPreserveGroups(ws.isPro);setSkipDuplicates(false);setSheet('restore')};
 const dismissRecovery=async()=>{try{if(recovery)await chrome.storage.local.set({tv_crash_dismissed:recovery.id});await chrome.storage.local.remove('tv_startup_hint');setRecovery(null)}catch{notify(t('saveFailed'))}};
 const restore=async(here=false)=>{const result=await run('RESTORE',{id:selected,here,windowId:ws.windowInfo.id,indices,preserveGroups:ws.isPro&&preserveGroups,skipDuplicates:ws.isPro&&skipDuplicates});if(result){setSheet(null);notify(t('restoredDetailed',{n:result.restored,skipped:result.skipped}));if(selected===recovery?.id)await dismissRecovery();ws.refreshTabs()}};
 const openProject=async()=>{if(project==='all'||!project)return;const result=await run('RESTORE_PROJECT',{id:project,skipDuplicates:true});if(result){notify(t('projectWindowsOpened',{n:result.restored,windows:result.windows}));ws.refreshTabs()}};
 const exportBackup=async()=>{
  if(format!=='json'&&!ws.isPro)return upgrade('organizePro');const date=dayOf(Date.now()),sessions=state.sessions;
  if(format==='json')download(JSON.stringify({app:'tabvault',v:2,sessions,projects},null,2),'tabvault-'+date+'.json');
  else if(format==='md'){const esc=value=>String(value).replace(/[\\\[\]]/g,'\\$&');download(sessions.map(session=>'## '+esc(session.name)+'\n\n'+session.tabs.map(tab=>'- ['+esc(tab.title)+']('+tab.url.replaceAll('(','%28').replaceAll(')','%29')+')').join('\n')).join('\n\n'),'tabvault-'+date+'.md','text/markdown')}
  else if(format==='csv'){const cell=value=>{const raw=String(value??'');return '"'+(/^[=+\-@\t\r]/.test(raw)?"'":'')+raw.replaceAll('"','""')+'"'};const rows=[['session','project','created','note','tags','tab_title','tab_url'],...sessions.flatMap(session=>session.tabs.map(tab=>[session.name,projects.find(project=>project.id===session.projectId)?.name||'',new Date(session.createdAt).toISOString(),session.note,session.tags.join(', '),tab.title,tab.url]))];download('\ufeff'+rows.map(row=>row.map(cell).join(',')).join('\r\n'),'tabvault-'+date+'.csv','text/csv')}
  else{try{await navigator.clipboard.writeText(sessions.map(session=>session.name+'\n'+session.tabs.map(tab=>tab.url).join('\n')).join('\n\n'));return notify(t('copied'))}catch{return notify(t('copyFailed'))}}
  notify(t('backupReady'));
 };
 const importFile=async file=>{if(!file)return;if(file.size>10*1024*1024)return notify(t('largeFile'));try{const data=JSON.parse(await file.text());if(data.app&&data.app!=='tabvault')throw new Error();const result=await run('IMPORT',{data});if(result)notify(t('importSessions',{n:result.imported}))}catch{notify(t('badFile',{app:'TabVault'}))}finally{fileRef.current.value=''}};
 const toggleSelected=id=>setChecked(ids=>ids.includes(id)?ids.filter(value=>value!==id):[...ids,id]);
 if(!ws.ready||ws.error)return <Loading ws={ws}/>;
 return <section className="app-panel" ref={panelRef} aria-label="TabVault"><Header ws={ws} onSettings={settings}/><main className="app-scroll"><Welcome ws={ws}/>{state.recoveryAvailable&&<div className="notice-banner">{t('recoveryData')}</div>}
  <div className="project-toolbar"><label><Folder size={15}/><select aria-label={t('projects')} value={project} onChange={event=>setProject(event.target.value)}><option value="all">{t('allProjects')}</option><option value="">{t('ungrouped')}</option>{projects.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Button variant="ghost" size="icon" aria-label={t('projects')} onClick={()=>setSheet('projects')}><Plus size={16}/></Button></div>
  {project&&project!=='all'&&<Button className="wide-action" variant="outline" disabled={busy} onClick={openProject}>{t('openProject')}<Layers3 size={15}/></Button>}
  <section className="window-card"><div className="window-card-head"><span className="window-card-title"><Monitor size={16}/>{t('currentWindow')}</span><span className="count-pill">{t('tabs',{n:sessionsTabs.length})}</span></div><div className="window-sites"><SiteStack tabs={sessionsTabs}/><div><b>{hosts.slice(0,3).join(' · ')||t('noTabs')}</b><span>{t('morePages',{n:Math.max(0,sessionsTabs.length-3)})} · {t('pinned',{n:sessionsTabs.filter(tab=>tab.pinned).length})}</span></div></div><Button id="btnSave" className="primary-action" disabled={busy||!sessionsTabs.length} onClick={()=>saveWindow()}><Archive/>{t('saveWindow')}<span className="shortcut">Alt ⇧ S</span></Button><Button id="btnSaveClose" variant="ghost" className="save-close" disabled={busy||!sessionsTabs.length} onClick={()=>saveWindow(true)}>{t('saveClose')}<ArrowUpRight size={13}/></Button></section>
  <AnimatePresence>{recovery&&<motion.section key="recovery" className="recovery-card" initial={false} exit={{height:0,opacity:0}} transition={ws.transition}><RotateCcw size={16}/><div><b>{t('recoveryTitle')}</b><span>{recovery.name} · {t('tabs',{n:recovery.tabs.length})}</span></div><Button variant="ghost" onClick={()=>openRestore(recovery)}>{t('restore')}</Button><Button variant="ghost" size="icon-xs" aria-label={t('dismiss')} onClick={dismissRecovery}><X size={12}/></Button></motion.section>}</AnimatePresence>
  <div className="list-controls"><Segments value={filter} onChange={setFilter} label={t('sessions')} items={[{id:'all',label:t('all'),count:state.sessions.length},{id:'manual',label:t('manual')},{id:'auto',label:t('timeline')}]}/><Button variant="ghost" size="icon-xs" aria-label={t('advancedFilters')} onClick={()=>ws.isPro?setShowFilters(!showFilters):upgrade('historyPro')}><Filter size={15}/></Button><Button variant="ghost" size="icon-xs" aria-label={t('batchOrganize')} onClick={()=>ws.isPro?setBatch(!batch):upgrade('organizePro')}><Layers3 size={15}/></Button></div>
  <div className="search-box"><Search size={14}/><input id="search" aria-label={t('searchVaultLabel')} value={query} onChange={event=>setQuery(event.target.value)} placeholder={t('searchSessions')}/>{query&&<Button variant="ghost" size="icon-xs" aria-label={t('clearSearch')} onClick={()=>setQuery('')}><X size={12}/></Button>}</div>
  {showFilters&&<div className="history-filters"><label className="form-label">{t('fromDate')}<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label className="form-label">{t('toDate')}<input type="date" min={from} value={to} onChange={event=>setTo(event.target.value)}/></label><label className="form-label">{t('filterTag')}<input value={tag} onChange={event=>setTag(event.target.value)}/></label></div>}
  {filter==='auto'&&<p className="settings-note">{t(ws.isPro?'historyRetention':'freeRetention')}</p>}
  {batch&&checked.length>0&&<div className="batch-actions"><b>{t('selectedSessions',{n:checked.length})}</b><select aria-label={t('moveToProject')} value="" onChange={async event=>{const projectId=event.target.value==='__none'?'':event.target.value;if(await run('BULK_MOVE',{ids:checked,projectId})){setChecked([]);notify(t('sessionsMoved'))}}}><option value="" disabled>{t('moveToProject')}</option><option value="__none">{t('ungrouped')}</option>{projects.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select><Button variant="outline" disabled={busy||checked.length<2} onClick={async()=>{if(confirm(t('confirmMerge'))&&await run('MERGE',{ids:checked,projectId:project==='all'?'':project})){setChecked([]);notify(t('merged'))}}}>{t('mergeSessions')}</Button></div>}
  <div className="list-heading"><span>{t(filter==='auto'?'timeline':'recent')}</span><span>{t('sessionCount',{n:visible.length})}{!ws.isPro&&<small> · {manualCount}/{caps.maxManualSessions}</small>}</span></div>
  <div className="session-list"><AnimatePresence initial={false}>{visible.map((session,index)=><React.Fragment key={session.id}>{filter==='auto'&&(index===0||dayOf(visible[index-1].createdAt)!==dayOf(session.createdAt))&&<div className="timeline-day">{dayOf(session.createdAt)}</div>}<motion.article layout initial={{opacity:0,y:6}} animate={{opacity:1,y:0}} exit={{opacity:0,scale:.98}} transition={ws.transition} className="session-card" data-id={session.id}><div className="session-card-main">{batch&&!session.auto&&<input type="checkbox" aria-label={t('selectSession',{name:session.name})} checked={checked.includes(session.id)} onChange={()=>toggleSelected(session.id)}/>}<span className="session-folder"><Folder size={20}/></span><button className="session-title-block" aria-label={t('expand',{name:session.name})} aria-expanded={expanded===session.id} onClick={()=>setExpanded(expanded===session.id?null:session.id)}><b>{session.pinned&&<Pin size={11}/>} {session.name}</b><span>{t('tabs',{n:session.tabs.length})} · {ago(session.createdAt,ws)}{session.projectId&&' · '+(projects.find(item=>item.id===session.projectId)?.name||t('ungrouped'))}</span></button><Button variant="ghost" size="icon-xs" aria-label={t('editSession',{name:session.name})} onClick={()=>{setSelected(session.id);setSheet('session')}}><MoreHorizontal size={15}/></Button></div><div className="session-card-foot"><SiteStack tabs={session.tabs}/><span>{t(session.auto?'autoSnapshot':'manualSaved')}</span><Button variant="ghost" className="session-restore" onClick={()=>openRestore(session)}>{t('restore')}<ArrowUpRight size={13}/></Button></div>{expanded===session.id&&<div className="session-tabs">{session.tabs.map((tab,index)=><a key={index} href={tab.url} target="_blank" rel="noopener noreferrer"><span>{tab.title}</span><small>{domain(tab.url)}{tab.group?' · '+tab.group.title:''}</small></a>)}</div>}</motion.article></React.Fragment>)}</AnimatePresence></div>{!visible.length&&<Empty ws={ws} search={!!query||!!from||!!to||!!tag}/>}
  <div className="backup-status"><ShieldCheck size={13}/><span>{t(state.settings.autoOn?'autoOn':'autoOff')}</span><Button variant="ghost" onClick={settings}>{t('settings')}</Button></div>
 </main><Footer ws={ws} onExport={exportBackup} onImport={()=>fileRef.current?.click()}><Button variant="ghost" size="icon-xs" id="btnPaste" aria-label={t('paste')} onClick={()=>setSheet('paste')}><Link2 size={14}/></Button></Footer><input id="fileImport" type="file" hidden ref={fileRef} accept=".json,application/json" onChange={event=>importFile(event.target.files?.[0])}/>{!sheet&&<Toast ws={ws}/>}
 <PanelSheet ws={ws} panelRef={panelRef} open={!!sheet} onClose={()=>setSheet(null)} title={t(sheet==='upgrade'?'upgradeTitle':sheet==='projects'?'projects':sheet==='settings'?'settingsTitle':sheet==='restore'?'restoreTitle':sheet==='paste'?'pasteTitle':'renameTitle')} description={t(sheet==='upgrade'?'upgradeDesc':sheet==='settings'?'settingsDesc':sheet==='restore'?'restoreDesc':sheet==='paste'?'pasteDesc':'local')}>
  {sheet==='settings'&&<><SettingsBrand ws={ws}/><Preferences ws={ws}/><VaultSettings ws={ws} run={run}/><DataSettings ws={ws} onExport={exportBackup} onImport={()=>fileRef.current?.click()}/><label className="form-label">{t('exportFormat')}<select value={format} onChange={async event=>{const value=event.target.value;try{await chrome.storage.local.set({tv_export_format:value});setFormat(value)}catch{notify(t('saveFailed'))}}}><option value="json">JSON</option><option value="md">Markdown · Pro</option><option value="csv">CSV · Pro</option><option value="txt">{t('copy')} · Pro</option></select></label><License ws={ws} onUpgrade={()=>upgrade()}/><Shortcuts ws={ws}/></>}
  {sheet==='upgrade'&&<UpgradePanel ws={ws} reason={reason}/>}{sheet==='projects'&&<ProjectPanel ws={ws} run={run}/>}
  {sheet==='restore'&&(picked?<><div className="restore-summary"><Folder size={28}/><h3>{picked.name}</h3><p>{t('tabs',{n:picked.tabs.length})} · {ago(picked.createdAt,ws)}</p></div><p className="settings-note">{t('restoreScope')}</p><label className="restore-option"><input type="checkbox" checked={indices.length===picked.tabs.length} onChange={event=>setIndices(event.target.checked?picked.tabs.map((_,index)=>index):[])}/>{t('selectAllTabs')}</label><div className="restore-tab-list" aria-label={t('selectTabs')}>{picked.tabs.map((tab,index)=><label key={index}><input type="checkbox" checked={indices.includes(index)} onChange={()=>setIndices(values=>values.includes(index)?values.filter(value=>value!==index):[...values,index])}/><span>{tab.title}<small>{domain(tab.url)}</small></span></label>)}</div><label className="restore-option"><input type="checkbox" checked={ws.isPro&&preserveGroups} onChange={event=>ws.isPro?setPreserveGroups(event.target.checked):upgrade('restorePro')}/>{t('preserveGroups')}</label><label className="restore-option"><input type="checkbox" checked={ws.isPro&&skipDuplicates} onChange={event=>ws.isPro?setSkipDuplicates(event.target.checked):upgrade('restorePro')}/>{t('skipDuplicates')}</label><Button variant="outline" className="restore-choice" disabled={busy||!indices.length} onClick={()=>restore(false)}><Monitor/><div><b>{t('newWindow')}</b><span>{t('newWindowDesc')}</span></div><ArrowUpRight/></Button><Button variant="outline" className="restore-choice" disabled={busy||!indices.length||ws.windowInfo.id==null} onClick={()=>restore(true)}><Layers3/><div><b>{t('here')}</b><span>{t('hereDesc')}</span></div><Plus/></Button><div className="quiet-info"><ShieldCheck size={15}/><span>{t(state.settings.delAfterRestore&&!picked.auto&&indices.length===picked.tabs.length&&!skipDuplicates?'removedSession':'keptSession')}</span></div></>:<Empty ws={ws}/>)}
  {sheet==='session'&&<SessionEditor key={selected} ws={ws} session={picked} run={run} onClose={()=>setSheet(null)}/>}
  {sheet==='paste'&&<PastePanel ws={ws} run={run} projectId={project==='all'?'':project} onSaved={()=>{setFilter('all');setQuery('');setSheet(null)}}/>}
 </PanelSheet></section>;
}
function VaultSettings({ws,run}){const [interval,setInterval]=useState(String(ws.state.settings.intervalMin)),{t,state}=ws;return <div className="settings-section"><h4>{t('backup')}</h4><div className="preference-row"><div><b>{t('autoBackup')}</b><span>{t('backupSchedule',{n:state.settings.intervalMin,max:ws.caps.keepAutoBackups})}</span></div><Switch aria-label={t('autoBackup')} checked={state.settings.autoOn} disabled={ws.busy} onCheckedChange={value=>run('SETTINGS',{autoOn:value})}/></div><p className="settings-note">{t(ws.isPro?'historyRetention':'freeRetention')}</p><form style={{marginTop:18}} onSubmit={async event=>{event.preventDefault();if(await run('SETTINGS',{intervalMin:Number(interval)}))ws.notify(t('preferencesSaved'))}}><label className="form-label">{t('interval')}<input type="number" min="1" step="1" value={interval} onChange={event=>setInterval(event.target.value)}/></label><Button variant="outline" type="submit" disabled={ws.busy||!interval||!Number.isFinite(Number(interval))||Number(interval)<1}>{t('save')}</Button></form><div className="preference-row" style={{marginTop:22}}><div><b>{t('deleteAfter')}</b><span>{t('deleteAfterNote')}</span></div><Switch aria-label={t('deleteAfter')} checked={state.settings.delAfterRestore} disabled={ws.busy} onCheckedChange={value=>run('SETTINGS',{delAfterRestore:value})}/></div></div>}
function ProjectPanel({ws,run}){const [name,setName]=useState(''),[note,setNote]=useState(''),[color,setColor]=useState('#11836e'),{t}=ws;return <><p className="settings-note">{t('proVaultLead')}</p>{(ws.state.projects||[]).map(project=><ProjectEditor key={project.id} project={project} ws={ws} run={run}/>)}<form className="settings-section" onSubmit={async event=>{event.preventDefault();if(await run('PROJECT_ADD',{name:name.trim(),note,color})){setName('');setNote('');ws.notify(t('projectCreated'))}}}><h4>{t('newProject')}</h4><label className="form-label">{t('projectName')}<input maxLength={80} required value={name} onChange={event=>setName(event.target.value)}/></label><label className="form-label">{t('projectNote')}<textarea rows={2} maxLength={2000} value={note} onChange={event=>setNote(event.target.value)}/></label><label className="form-label">{t('projectColor')}<input type="color" value={color} onChange={event=>setColor(event.target.value)}/></label><Button type="submit" className="primary-action" disabled={ws.busy||!name.trim()}>{t('newProject')}<Plus size={15}/></Button></form></>}
function ProjectEditor({project,ws,run}){const [name,setName]=useState(project.name),[note,setNote]=useState(project.note),[color,setColor]=useState(project.color),{t}=ws;return <details className="project-editor"><summary><span style={{background:color}}/>{project.name}</summary><label className="form-label">{t('projectName')}<input value={name} maxLength={80} onChange={event=>setName(event.target.value)}/></label><label className="form-label">{t('projectNote')}<textarea value={note} maxLength={2000} rows={2} onChange={event=>setNote(event.target.value)}/></label><label className="form-label">{t('projectColor')}<input type="color" value={color} onChange={event=>setColor(event.target.value)}/></label><div className="setting-data-actions"><Button variant="outline" disabled={ws.busy||!name.trim()} onClick={async()=>{if(await run('PROJECT_PATCH',{id:project.id,name,note,color}))ws.notify(t('projectUpdated'))}}>{t('save')}</Button><Button variant="outline" onClick={async()=>{if(confirm(t('confirmDeleteProject'))&&await run('PROJECT_DELETE',{id:project.id}))ws.notify(t('projectDeleted'))}}>{t('delete')}</Button></div></details>}
function SessionEditor({ws,session,run,onClose}){const [name,setName]=useState(session?.name||''),[note,setNote]=useState(session?.note||''),[tags,setTags]=useState(session?.tags?.join(', ')||''),[projectId,setProjectId]=useState(session?.projectId||''),[pinned,setPinned]=useState(!!session?.pinned),{t}=ws;if(!session)return <Empty ws={ws}/>;return <><div className="session-edit-summary"><SiteStack tabs={session.tabs}/><span>{t('tabs',{n:session.tabs.length})} · {ago(session.createdAt,ws)}</span></div><label className="form-label">{t('rename')}<input maxLength={200} disabled={session.auto} value={name} onChange={event=>setName(event.target.value)}/></label>{!session.auto&&<><label className="form-label">{t('projects')}<select disabled={!ws.isPro} value={projectId} onChange={event=>setProjectId(event.target.value)}><option value="">{t('ungrouped')}</option>{(ws.state.projects||[]).map(project=><option value={project.id} key={project.id}>{project.name}</option>)}</select></label><label className="form-label">{t('note')} · Pro<textarea disabled={!ws.isPro} value={note} rows={3} maxLength={10000} onChange={event=>setNote(event.target.value)}/></label><label className="form-label">{t('tags')} · Pro<input disabled={!ws.isPro} value={tags} onChange={event=>setTags(event.target.value)}/></label><label className="restore-option"><input type="checkbox" disabled={!ws.isPro} checked={pinned} onChange={event=>setPinned(event.target.checked)}/>{t('pinSession')}</label><Button className="primary-action" disabled={ws.busy||!name.trim()} onClick={async()=>{if(await run(ws.isPro?'SESSION_PATCH':'RENAME',{id:session.id,name:name.trim(),...(ws.isPro?{note,tags:tags.split(/[,，]/).map(value=>value.trim()).filter(Boolean),projectId,pinned}:{})})){onClose();ws.notify(t('sessionUpdated'))}}}>{t('save')}<Check size={15}/></Button><Button variant="outline" className="wide-action" disabled={ws.busy} onClick={async()=>{if(confirm(t('confirmDedup'))){const result=await run('DEDUP',{id:session.id});if(result)ws.notify(t('duplicatesRemoved',{n:result.removed}))}}}>{t('deduplicate')}</Button><Button variant="outline" className="danger-action" disabled={ws.busy} onClick={async()=>{if(confirm(t('confirmDeleteSession'))&&await run('DELETE',{id:session.id})){onClose();ws.notify(t('deleted'))}}}><Trash2 size={14}/>{t('deleteSession')}</Button></>}</>}
function PastePanel({ws,run,projectId,onSaved}){const [input,setInput]=useState(''),[working,setWorking]=useState(false),{t}=ws;const save=async()=>{const urls=parseLinks(input);if(!urls.length)return ws.notify(t('pasteNone'));const tabs=urls.map(url=>({title:domain(url)+new URL(url).pathname,url,fav:'',pinned:false}));if(await run('PASTE',{tabs,projectId})){ws.notify(t('savedWindow',{n:tabs.length}));onSaved()}};const open=async()=>{const urls=parseLinks(input);if(!urls.length)return ws.notify(t('pasteNone'));setWorking(true);let opened=0;try{for(const url of urls){await chrome.tabs.create({windowId:ws.windowInfo.id,url,active:false});opened++}ws.notify(t('opened',{n:opened}));ws.refreshTabs();onSaved()}catch{ws.notify(t('partialOpen',{n:opened,total:urls.length}))}finally{setWorking(false)}};return <><label className="form-label">{t('webLinks')}<textarea id="pasteInput" rows={7} value={input} onChange={event=>setInput(event.target.value)} placeholder={'https://example.com/article\nexample.org\n'+t('search')} disabled={working}/></label><Button id="btnPasteSave" className="primary-action" disabled={ws.busy||working||!input.trim()} onClick={save}><Archive size={16}/>{t('saveAsSession')}</Button><Button id="btnPasteOpen" variant="outline" className="wide-action" disabled={working||!input.trim()||ws.windowInfo.id==null} onClick={open}>{t('openLinks')}<ArrowUpRight size={14}/></Button></>}
