import assert from 'node:assert/strict';
import vm from 'node:vm';
import {fixture} from './billing.test.mjs';
const tests=[];const test=(name,fn)=>tests.push([name,fn]);
const token='a'.repeat(64),different='b'.repeat(64);
test('Purchase pairing is hashed and retries reuse the same Checkout Session',async e=>{
 assert.equal((await e.request('/checkout?claim='+token,{method:'POST'})).status,303);const initial=[...e.sessions.values()][0];assert.equal((await e.request('/checkout?claim='+token,{method:'POST'})).status,303);assert.equal(e.sessions.size,1);const claim=await e.db.prepare('SELECT * FROM activation_claims').first();assert.notEqual(claim.token_hash,token);assert.equal((await(await e.request('/api/activation?token='+token)).json()).status,'pending');e.pay(initial);const result=await(await e.request('/api/activation?token='+token)).json();assert.equal(result.status,'paid');assert(result.key);assert.equal(result.sid,initial.id);assert.equal((await(await e.request('/api/activation?token='+different)).json()).key,undefined);
});
test('Wrong product, refunds, expired claims and unpaid delayed payments cannot activate',async e=>{
 await e.request('/checkout?claim='+token,{method:'POST'});const session=[...e.sessions.values()][0];session.status='complete';assert.equal((await(await e.request('/api/activation?token='+token)).json()).status,'pending');e.pay(session);session.metadata.app='other';assert.equal((await e.request('/api/activation?token='+token)).status,400);session.metadata.app=e.env.PRODUCT_SLUG;session.payment_intent.latest_charge.amount_refunded=600;assert.equal((await e.request('/api/activation?token='+token)).status,400);await e.db.prepare('UPDATE activation_claims SET expires_at=1').run();assert.equal((await e.request('/api/activation?token='+token)).status,410);
});
test('Success-page notification script is valid and carries only a purchase capability',async e=>{
 await e.request('/checkout?claim='+token,{method:'POST'});const session=e.pay([...e.sessions.values()][0]);e.env.EXTENSION_ID='a'.repeat(32);const page=await(await e.request('/success?sid='+session.id+'&claim='+token)).text();assert(page.includes('data-claim="'+token+'"'));const script=await(await e.request('/assets/billing.js')).text();new vm.Script(script);assert(script.includes("type:'BILLING_COMPLETE'"));assert(script.includes('chrome.runtime.lastError'));assert(!script.includes(e.env.LIC_SECRET));
});
test('Recovery verifies email ownership and consumes each code once',async e=>{
 e.env.RESEND_API_KEY='test-mail-key';e.env.BILLING_EMAIL_FROM='Pro <billing@example.com>';const sent=[];const stripe=e.fetch;globalThis.fetch=async(url,options)=>{if(new URL(url).hostname==='api.resend.com'){sent.push(JSON.parse(options.body));return Response.json({id:'mail_fixture'})}return stripe(url,options)};
 const session=e.pay(await e.checkout());session.customer_details={email:'buyer@example.com'};await e.request('/success?sid='+session.id);const started=await(await e.request('/api/recovery/request',{method:'POST',body:{email:'Buyer@example.com'}})).json();assert.equal(sent.length,1);const code=sent[0].text.match(/\b\d{6}\b/)[0];assert.equal((await e.request('/api/recovery/verify',{method:'POST',body:{id:started.recoveryId,code:'invalid'}})).status,400);const verified=await e.request('/api/recovery/verify',{method:'POST',body:{id:started.recoveryId,code}});assert.equal(verified.status,200);assert((await verified.json()).key);assert.equal((await e.request('/api/recovery/verify',{method:'POST',body:{id:started.recoveryId,code}})).status,400);
 const stored=await e.db.prepare('SELECT * FROM recovery_requests').first();assert(!JSON.stringify(stored).includes('buyer@example.com'));assert.notEqual(stored.code_hash,code);assert.equal((await e.request('/api/recovery/request',{method:'POST',body:{email:'buyer@example.com'}})).status,429);
});
test('Unknown emails do not reveal purchase existence and invalid guesses stop after five attempts',async e=>{
 e.env.RESEND_API_KEY='test-mail-key';e.env.BILLING_EMAIL_FROM='billing@example.com';const response=await e.request('/api/recovery/request',{method:'POST',body:{email:'unknown@example.com'}});assert.equal(response.status,200);const {recoveryId}=await response.json();for(let index=0;index<6;index++)assert.equal((await e.request('/api/recovery/verify',{method:'POST',body:{id:recoveryId,code:'000000'}})).status,400);assert.equal((await e.db.prepare('SELECT * FROM recovery_requests').first()).attempts,5);
});
test('Missing email delivery configuration is explicit and does not affect automatic activation',async e=>{assert.equal((await e.request('/api/recovery/request',{method:'POST',body:{email:'buyer@example.com'}})).status,503);await e.request('/checkout?claim='+token,{method:'POST'});e.pay([...e.sessions.values()][0]);assert.equal((await(await e.request('/api/activation?token='+token)).json()).status,'paid')});
test('Expired and newly refunded email purchases cannot recover Pro',async e=>{
 e.env.RESEND_API_KEY='test-mail-key';e.env.BILLING_EMAIL_FROM='billing@example.com';const sent=[],stripe=e.fetch;globalThis.fetch=async(url,options)=>new URL(url).hostname==='api.resend.com'?(sent.push(JSON.parse(options.body)),Response.json({id:'fixture'})):stripe(url,options);
 const session=e.pay(await e.checkout());session.customer_details={email:'buyer@example.com'};await e.request('/success?sid='+session.id);const first=await(await e.request('/api/recovery/request',{method:'POST',body:{email:'buyer@example.com'}})).json(),code=sent[0].text.match(/\b\d{6}\b/)[0];await e.db.prepare('UPDATE recovery_requests SET expires_at=1,created_at=1').run();assert.equal((await e.request('/api/recovery/verify',{method:'POST',body:{id:first.recoveryId,code}})).status,400);
 const next=await(await e.request('/api/recovery/request',{method:'POST',body:{email:'buyer@example.com'}})).json(),newCode=sent[1].text.match(/\b\d{6}\b/)[0];session.payment_intent.latest_charge.amount_refunded=600;assert.equal((await e.request('/api/recovery/verify',{method:'POST',body:{id:next.recoveryId,code:newCode}})).status,400);assert.equal((await e.db.prepare('SELECT * FROM recovery_requests WHERE id=?').bind(next.recoveryId).first()).verified_at,null);
});
let failed=0;const original=globalThis.fetch;try{for(const[name,fn]of tests){const e=fixture();globalThis.fetch=e.fetch;try{await fn(e);console.log('PASS '+name)}catch(error){failed++;console.error('FAIL '+name+'\n'+error.stack)}finally{e.db.sqlite.close()}}}finally{globalThis.fetch=original}console.log(`Activation: ${tests.length-failed}/${tests.length} passed`);process.exitCode=failed?1:0;
