import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {DatabaseSync} from 'node:sqlite';
import {webcrypto} from 'node:crypto';
import worker,{computeKey} from './index.js';
globalThis.crypto??=webcrypto;
const directory=path.dirname(fileURLToPath(import.meta.url)),slug=/PRODUCT_SLUG = "([^"]+)"/.exec(fs.readFileSync(path.join(directory,'wrangler.toml'),'utf8'))[1];
export function database(){
 const sqlite=new DatabaseSync(':memory:');sqlite.exec(fs.readFileSync(path.join(directory,'migrations/0001_orders.sql'),'utf8'));
 const adapter={sqlite,fail:false,prepare(sql){let args=[];return{bind(...values){args=values;return this},async first(){if(adapter.fail)throw new Error('storage failure');return sqlite.prepare(sql).get(...args)||null},async all(){if(adapter.fail)throw new Error('storage failure');return{results:sqlite.prepare(sql).all(...args)}},async run(){if(adapter.fail)throw new Error('storage failure');return{success:true,meta:sqlite.prepare(sql).run(...args)}}}},async batch(statements){if(adapter.fail)throw new Error('storage failure');sqlite.exec('BEGIN');try{const output=[];for(const statement of statements)output.push(await statement.run());sqlite.exec('COMMIT');return output}catch(error){sqlite.exec('ROLLBACK');throw error}}};return adapter;
}
export function fixture(){
 const db=database(),requests=[],sessions=new Map(),items=new Map(),links=new Map(),charges=new Map();let seq=0,failure=null;
 const env={PRODUCT_SLUG:slug,PRODUCT_NAME:slug+' Pro',PUBLIC_ORIGIN:'https://billing.example',STRIPE_SECRET_KEY:'test-private-stripe',LIC_SECRET:'test-private-license',ADMIN_TOKEN:'test-private-admin',STRIPE_WEBHOOK_SECRET:'whsec_test_private',STRIPE_PAYMENT_LINK:'https://buy.stripe.com/OWN',STRIPE_PRICE_ID:'price_OWN',ALLOW_TEST_PAYMENTS:'false',CHECKOUT_MODE:'api',ORDERS_DB:db,ENABLE_PROVISIONING:'false'};
 const price={object:'price',id:'price_OWN',product:'prod_OWN',active:true,type:'one_time',unit_amount:600,currency:'usd',livemode:true,recurring:null};
 links.set('plink_OWN',{object:'payment_link',id:'plink_OWN',url:env.STRIPE_PAYMENT_LINK,livemode:true,allow_promotion_codes:true});
 const fetch=async(raw,options={})=>{
  const url=new URL(raw),params=new URLSearchParams(options.body),method=options.method||'GET';assert.equal(url.origin,'https://api.stripe.com');assert.equal(options.headers.Authorization,'Bearer '+env.STRIPE_SECRET_KEY);requests.push({path:url.pathname,method,params,headers:options.headers});
  if(failure&&url.pathname.includes(failure))return new Response('{}',{status:500});
  let result;
  if(url.pathname==='/v1/prices/price_OWN')result=price;
  else if(url.pathname==='/v1/checkout/sessions'&&method==='POST'){
   const sid='cs_live_fixture'+(++seq).toString().padStart(6,'0');result={object:'checkout.session',id:sid,status:'open',mode:'payment',payment_status:'unpaid',livemode:price.livemode,url:'https://checkout.stripe.com/c/pay/'+sid,amount_subtotal:600,amount_total:600,currency:'usd',client_reference_id:params.get('client_reference_id'),metadata:{app:params.get('metadata[app]'),order_id:params.get('metadata[order_id]'),flow:params.get('metadata[flow]')},payment_intent:null,created:Math.floor(Date.now()/1000)};sessions.set(sid,result);items.set(sid,{object:'list',data:[{quantity:1,price:structuredClone(price)}],has_more:false});
  }else if(url.pathname==='/v1/checkout/sessions')result={object:'list',data:[...sessions.values()].filter(session=>{const intent=typeof session.payment_intent==='object'?session.payment_intent?.id:session.payment_intent;return intent===url.searchParams.get('payment_intent')}),has_more:false};
  else if(url.pathname.endsWith('/line_items')){const id=url.pathname.split('/').at(-2);result=items.get(id)||{object:'list',data:[{quantity:1,price}],has_more:false}}
  else if(url.pathname.endsWith('/expire')){const session=sessions.get(url.pathname.split('/').at(-2));if(!session||session.status!=='open')return new Response('{}',{status:400});session.status='expired';result=session}
  else if(url.pathname.startsWith('/v1/checkout/sessions/'))result=sessions.get(url.pathname.split('/').at(-1));
  else if(url.pathname==='/v1/payment_links')result={object:'list',data:[...links.values()],has_more:false};
  else if(url.pathname.startsWith('/v1/payment_links/'))result=links.get(url.pathname.split('/').at(-1));
  else if(url.pathname.startsWith('/v1/charges/'))result=charges.get(url.pathname.split('/').at(-1));
  else if(url.pathname==='/v1/webhook_endpoints'&&method==='POST')result={object:'webhook_endpoint',id:'we_fixture',url:params.get('url'),livemode:true,secret:'whsec_fixture_provision'};
  if(!result)return new Response('{}',{status:404});return Response.json(result);
 };
 const request=async(route,{method='GET',admin=false,body,headers={}}={})=>worker.fetch(new Request('https://billing.example'+route,{method,headers:{...(admin?{authorization:'Bearer '+env.ADMIN_TOKEN}:{}),...headers},body:body===undefined?undefined:typeof body==='string'?body:JSON.stringify(body)}),env);
 const checkout=async()=>{const response=await request('/checkout',{method:'POST'});assert.equal(response.status,303);return[...sessions.values()].at(-1)};
 const pay=session=>{session.status='complete';session.payment_status='paid';const id='ch_'+session.id.replace(/_/g,''),intent='pi_'+session.id.replace(/_/g,'');const charge={object:'charge',id,payment_intent:intent,livemode:true,amount_refunded:0};charges.set(id,charge);session.payment_intent={id:intent,latest_charge:charge};return session};
 const event=(session,type='checkout.session.completed')=>({id:'evt_'+(++seq),type,created:Math.floor(Date.now()/1000),livemode:true,data:{object:{id:session.id}}});
 const sendEvent=async(event,{age=0,signatureOverride,rawOverride}={})=>{const raw=rawOverride||JSON.stringify(event),stamp=Math.floor(Date.now()/1000)+age,key=await crypto.subtle.importKey('raw',new TextEncoder().encode(env.STRIPE_WEBHOOK_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']),sig=Buffer.from(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(stamp+'.'+raw))).toString('hex');return request('/webhook',{method:'POST',body:raw,headers:{'stripe-signature':signatureOverride||`t=${stamp},v1=${sig}`}})};
 return{env,db,price,requests,sessions,items,links,charges,fetch,request,checkout,pay,event,sendEvent,setFailure:path=>failure=path};
}
const tests=[],test=(name,fn)=>tests.push([name,fn]);
test('Purchase consent page shows price and disclosure without recording an order',async e=>{const response=await e.request('/buy'),html=await response.text();assert.equal(response.status,200);assert(html.includes('$6.00'));assert(html.includes('Agree and continue to Stripe'));assert(html.includes('Cloudflare'));assert.equal((await e.db.prepare('SELECT COUNT(*) AS n FROM orders').first()).n,0);assert(!e.requests.some(r=>r.path==='/v1/checkout/sessions'&&r.method==='POST'));const zh=await(await e.request('/buy?lang=zh')).text();assert(zh.includes('同意并前往 Stripe 结账'))});
test('Checkout uses server price, preserves language, records order and ignores client price input',async e=>{const response=await e.request('/checkout?lang=zh&price=price_ATTACK&amount=1&success_url=https://evil.example',{method:'POST'});assert.equal(response.status,303);const creation=e.requests.find(r=>r.path==='/v1/checkout/sessions'&&r.method==='POST');assert.equal(creation.params.get('line_items[0][price]'),'price_OWN');assert.equal(creation.params.get('line_items[0][quantity]'),'1');assert.equal(creation.params.get('locale'),'zh');assert(creation.params.get('success_url').startsWith('https://billing.example/success?'));assert.equal(creation.params.get('adaptive_pricing[enabled]'),'false');assert(creation.headers['Idempotency-Key']);const order=await e.env.ORDERS_DB.prepare('SELECT * FROM orders').first();assert(order.session_id);assert.equal(order.checkout_status,'open');assert.equal(order.app,slug)});
test('D1 failure prevents creating a Stripe checkout',async e=>{e.db.fail=true;assert.equal((await e.request('/checkout',{method:'POST'})).status,503);assert.equal(e.requests.some(r=>r.path==='/v1/checkout/sessions'&&r.method==='POST'),false)});
test('Stripe creation failure records failure without issuing a license',async e=>{e.setFailure('/checkout/sessions');assert.equal((await e.request('/checkout',{method:'POST'})).status,502);const order=await e.db.prepare('SELECT * FROM orders').first();assert.equal(order.checkout_status,'creation_failed');assert.equal(order.fulfillment_status,'pending')});
test('Live service rejects test prices and inactive prices',async e=>{e.price.livemode=false;assert.equal((await e.request('/checkout',{method:'POST'})).status,400);e.price.livemode=true;e.price.active=false;assert.equal((await e.request('/checkout',{method:'POST'})).status,400)});
test('Unpaid and expired checkout cannot issue a license',async e=>{const session=await e.checkout();assert.equal((await e.request('/success?sid='+session.id)).status,400);session.status='expired';assert.equal((await e.request('/success?sid='+session.id)).status,400)});
test('Verified paid API checkout issues the original deterministic license format',async e=>{const session=e.pay(await e.checkout());const response=await e.request('/success?sid='+session.id);assert.equal(response.status,200);const html=await response.text();assert(html.includes(await computeKey(e.env.LIC_SECRET,session.id)));assert.equal(response.headers.get('cache-control'),'no-store');assert(response.headers.get('content-security-policy').includes("script-src 'self'"));const order=await e.db.prepare('SELECT * FROM orders').first();assert.equal(order.fulfillment_status,'issued');assert(order.fulfilled_at);const payload=JSON.parse(Buffer.from((await computeKey(e.env.LIC_SECRET,session.id)).split('.')[0],'base64url'));assert.equal(payload.via,'stripe')});
test('Legacy Payment Link orders retain their license and are recorded',async e=>{const session={object:'checkout.session',id:'cs_live_legacy123',status:'complete',mode:'payment',payment_status:'paid',livemode:true,payment_link:'plink_OWN',amount_subtotal:600,amount_total:600,currency:'usd'};e.sessions.set(session.id,session);assert.equal((await e.request('/success?reference='+session.id)).status,200);const order=await e.db.prepare('SELECT * FROM orders').first();assert.equal(order.source,'payment_link');assert.equal(order.fulfillment_status,'issued')});
test('Different Payment Link and other-product sessions cannot issue licenses',async e=>{const session=e.pay(await e.checkout());session.metadata.app='other';assert.equal((await e.request('/success?sid='+session.id)).status,400);session.payment_link='plink_ATTACK';e.links.set('plink_ATTACK',{object:'payment_link',id:'plink_ATTACK',url:'https://buy.stripe.com/OTHER'});assert.equal((await e.request('/success?sid='+session.id)).status,400)});
test('Unknown API session cannot spoof metadata to obtain a license',async e=>{const known=e.pay(await e.checkout()),spoof=structuredClone(known);spoof.id='cs_live_spoof123';e.sessions.set(spoof.id,spoof);assert.equal((await e.request('/success?sid='+spoof.id)).status,400)});
test('Wrong price, quantity, currency, subtotal and product are rejected',async e=>{const session=e.pay(await e.checkout()),item=e.items.get(session.id).data[0];for(const alter of [()=>item.price.id='price_ATTACK',()=>item.quantity=2,()=>session.currency='eur',()=>session.amount_subtotal=1,()=>item.price.product='prod_ATTACK']){const originalSession=structuredClone(session),originalItem=structuredClone(item);alter();assert.equal((await e.request('/success?sid='+session.id)).status,400);Object.assign(session,originalSession);Object.assign(item,originalItem)}});
test('Authorized zero-total promotion can issue API license',async e=>{const session=await e.checkout();session.status='complete';session.payment_status='no_payment_required';session.amount_total=0;assert.equal((await e.request('/success?sid='+session.id)).status,200);assert.equal((await e.db.prepare('SELECT * FROM orders').first()).fulfillment_status,'issued')});
test('Bad, expired, future and changed webhook signatures are rejected',async e=>{const event=e.event(await e.checkout());for(const options of [{signatureOverride:'t=1,v1=bad'},{age:-301},{age:301},{signatureOverride:`t=${Math.floor(Date.now()/1000)},v1=${'0'.repeat(64)}`}])assert.equal((await e.sendEvent(event,options)).status,400);assert.equal((await e.db.prepare('SELECT COUNT(*) AS n FROM stripe_events').first()).n,0)});
test('Signed webhook fulfills without visiting the success page',async e=>{const session=e.pay(await e.checkout()),event=e.event(session);assert.equal((await e.sendEvent(event)).status,200);const order=await e.db.prepare('SELECT * FROM orders').first();assert.equal(order.fulfillment_status,'issued');assert.equal(order.payment_status,'paid')});
test('Webhook duplicate and concurrent delivery are idempotent',async e=>{const event=e.event(e.pay(await e.checkout()));const responses=await Promise.all([e.sendEvent(event),e.sendEvent(event)]);assert(responses.every(r=>r.status===200));assert.equal((await e.db.prepare('SELECT COUNT(*) AS n FROM stripe_events').first()).n,1);assert.equal((await e.db.prepare('SELECT COUNT(*) AS n FROM orders').first()).n,1);assert.equal((await(await e.sendEvent(event)).json()).duplicate,true)});
test('Webhook failure is retryable and never marks an event processed',async e=>{const event=e.event(e.pay(await e.checkout()));e.setFailure('/checkout/sessions');assert.equal((await e.sendEvent(event)).status,502);assert.equal((await e.db.prepare('SELECT COUNT(*) AS n FROM stripe_events').first()).n,0);e.setFailure(null);assert.equal((await e.sendEvent(event)).status,200)});
test('Test and unrelated-product webhook events are ignored safely',async e=>{const session=e.pay(await e.checkout()),event=e.event(session);event.livemode=false;assert.equal((await(await e.sendEvent(event)).json()).ignored,true);event.livemode=true;session.metadata.app='other';assert.equal((await(await e.sendEvent(event)).json()).ignored,true);assert.equal((await e.db.prepare('SELECT * FROM orders').first()).fulfillment_status,'pending')});
test('Delayed payment waits for paid state before issuance',async e=>{const session=await e.checkout();session.status='complete';assert.equal((await e.sendEvent(e.event(session))).status,200);assert.equal((await e.db.prepare('SELECT * FROM orders').first()).fulfillment_status,'pending');e.pay(session);assert.equal((await e.sendEvent(e.event(session,'checkout.session.async_payment_succeeded'))).status,200);assert.equal((await e.db.prepare('SELECT * FROM orders').first()).fulfillment_status,'issued')});
test('Refund callback records full refund even before checkout callback',async e=>{const session=e.pay(await e.checkout()),charge=session.payment_intent.latest_charge;charge.amount_refunded=600;const event=e.event(charge,'charge.refunded');assert.equal((await e.sendEvent(event)).status,200);const order=await e.db.prepare('SELECT * FROM orders').first();assert.equal(order.payment_status,'refunded');assert.equal(order.fulfillment_status,'pending');assert.equal((await e.request('/success?sid='+session.id)).status,400)});
test('Refund state survives older checkout event and prevents reissuance',async e=>{const session=e.pay(await e.checkout());await e.sendEvent(e.event(session));const charge=session.payment_intent.latest_charge;charge.amount_refunded=100;await e.sendEvent(e.event(charge,'charge.refunded'));charge.amount_refunded=0;await e.sendEvent(e.event(session));const order=await e.db.prepare('SELECT * FROM orders').first();assert.equal(order.payment_status,'partially_refunded');assert.equal(order.refunded_amount,100);assert.equal((await e.request('/success?sid='+session.id)).status,400)});
test('Order admin requires bearer token and does not accept URL token',async e=>{assert.equal((await e.request('/api/admin/orders')).status,401);assert.equal((await e.request('/api/admin/orders?token='+e.env.ADMIN_TOKEN)).status,401);const response=await e.request('/api/admin/orders',{admin:true});assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'no-store')});
test('Admin search, product isolation and same-second pagination work',async e=>{for(let i=0;i<5;i++)await e.checkout();const foreign=crypto.randomUUID();await e.db.prepare('INSERT INTO orders(id,app,created_at,updated_at) VALUES(?,?,?,?)').bind(foreign,'other',1,1).run();const first=await(await e.request('/api/admin/orders?limit=2',{admin:true})).json();assert.equal(first.orders.length,2);assert.equal(first.stats.total,5);const second=await(await e.request('/api/admin/orders?limit=2&cursor='+encodeURIComponent(first.next_cursor),{admin:true})).json();assert(second.orders.every(order=>!first.orders.some(prior=>prior.id===order.id)));const result=await(await e.request('/api/admin/orders?q='+first.orders[0].session_id,{admin:true})).json();assert.equal(result.orders.length,1);assert.equal((await e.request('/api/admin/orders?cursor=bad',{admin:true})).status,400)});
test('Admin can reconcile and recover paid license but cannot expire paid checkout',async e=>{const session=e.pay(await e.checkout());assert.equal((await e.request('/api/admin/reconcile',{admin:true,method:'POST',body:{sid:session.id}})).status,200);const response=await e.request('/api/admin/license',{admin:true,method:'POST',body:{sid:session.id}});assert.equal((await response.json()).key,await computeKey(e.env.LIC_SECRET,session.id));assert.equal((await e.request('/api/admin/expire',{admin:true,method:'POST',body:{sid:session.id}})).status,400)});
test('Admin can expire owned unpaid checkout and retain its record',async e=>{const session=await e.checkout();assert.equal((await e.request('/api/admin/expire',{admin:true,method:'POST',body:{sid:session.id}})).status,200);assert.equal((await e.db.prepare('SELECT * FROM orders').first()).checkout_status,'expired')});
test('Provisioning is authenticated, restricted and disabled after setup',async e=>{assert.equal((await e.request('/api/admin/provision',{method:'POST',admin:true})).status,403);e.env.ENABLE_PROVISIONING='true';assert.equal((await e.request('/api/admin/provision',{method:'POST'})).status,401);const response=await e.request('/api/admin/provision',{method:'POST',admin:true});assert.equal(response.status,200);const result=await response.json();assert.equal(result.price_id,'price_OWN');assert.equal(result.webhook_url,'https://billing.example/webhook');assert(result.webhook_secret.startsWith('whsec_'));assert.equal(e.requests.filter(r=>r.path==='/v1/webhook_endpoints'&&r.method==='POST').length,1)});
test('Public pages and status never include administrator or Stripe secrets',async e=>{for(const route of ['/','/admin','/admin?lang=zh','/status','/assets/billing.js']){const response=await e.request(route),body=await response.text();assert.equal(response.status,200);for(const secret of [e.env.ADMIN_TOKEN,e.env.STRIPE_SECRET_KEY,e.env.LIC_SECRET,e.env.STRIPE_WEBHOOK_SECRET])assert(!body.includes(secret))}});
test('Malformed checkout reference is rejected without a Stripe request',async e=>{assert.equal((await e.request('/success?sid=invalid')).status,400);assert.equal(e.requests.length,0)});
export async function runTests(){const original=globalThis.fetch;let failed=0;try{for(const[name,fn]of tests){const e=fixture();globalThis.fetch=e.fetch;try{await fn(e);console.log('PASS '+name)}catch(error){failed++;console.error('FAIL '+name+'\n'+error.stack)}finally{e.db.sqlite.close()}}}finally{globalThis.fetch=original}console.log(`${slug} billing: ${tests.length-failed}/${tests.length} passed`);return{passed:tests.length-failed,total:tests.length,failed}}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const result=await runTests();process.exitCode=result.failed?1:0}
